### PR TITLE
Readability improvements

### PR DESCRIPTION
**Pull request by pavlo-liapota**
I have tried to tidy a bit too. What do you think?

### CODE REVIEW

**Review by dmcg — APPROVED** [review]
This I like

**Review by dmcg — COMMENTED** [review]
Interesting. Personally I preferred the Int - I tend to reserve typealiases for things complicated generics or function types - `typealias PersonFinder = (ID<Person>) -> Person`

**Review by dmcg — COMMENTED** [review]
I had played with this inline myself, but came to the conclusion that `String.couldBeMadeFrom` was a nice abstraction.

**Comment by dmcg** [comment]
Sorry, I may have taken your question a little bit too literally! I hope that you were actually asking for feedback. 

These things are often very much a question of person preference. I prefer things in the way that make them easiest for me to understand, but know that my understanding doesn't always match others.

**Comment by dmcg** [comment]
Closed as #6 included these changes

**Comment by pavlo-liapota** [comment]
> These things are often very much a question of person preference. I prefer things in the way that make them easiest for me to understand, but know that my understanding doesn't always match others.

Yes, I agree.
But it is your project, so let's revert those changes? I just provide suggestions :)

**Pull request closed without merging**
