### PR TITLE
Represent letters that should be used to build anagram with Letters class

### PR DESCRIPTION
**Pull request by pavlo-liapota**
* `Letters` class stores count of each letter using `IntArray`
* This array allows to quickly check if any word can be made from these letters inside `couldBeMadeFromTheLettersIn()` function
* And this array allows to quickly calculate remaining letters using `minusLettersIn()` function

### CODE REVIEW

**Comment by pavlo-liapota** [comment]
I tried to implement my other optimizations (avoid `subList()` call and combine `couldBeMadeFromTheLettersIn()`, `minusLettersIn()` into one function) but failed to do it in a readable way. They don't provide a big benefit anyway.

**Comment by pavlo-liapota** [comment]
I tried to run test for `REFACTORING TO KOTLIN` without depth limit and it took more than 5 minutes.
It could be interesting to optimize for such big cases next.

**Comment by dmcg** [comment]
> I tried to implement my other optimizations (avoid `subList()` call and combine `couldBeMadeFromTheLettersIn()`, `minusLettersIn()` into one function) but failed to do it in a readable way. They don't provide a big benefit anyway.

I don’t think the sublist is expensive, but a better way of partitioning could let us run the code on multiple threads, which would be nice. 

I have also failed to combine those two functions in any way that didn’t make performance worse!

**Comment by dmcg** [comment]
> I tried to run test for `REFACTORING TO KOTLIN` without depth limit and it took more than 5 minutes.
> It could be interesting to optimize for such big cases next.

That’s a lot better than the 40 minutes it was taking me, although we will have different setups. I haven’t yet analysed the relationship between input length and time, but as we are (kind of) generating permutations it feels like O(n!)?

**Comment by pavlo-liapota** [comment]
> That’s a lot better than the 40 minutes it was taking me

Oh, by "it took more than 5 minutes" I meant that I waited for just 5 minutes and then stoped it. I didn't have a patience to wait :)

> but as we are (kind of) generating permutations it feels like O(n!)?

Yes, looks like it. But there are a lot of cases when we calculate the same thing many times. And the number is increasing with longer input.
There are a lot of words that are anagrams of each other. We can keep just one word from these groups, run the algorithm and then update output to use other words too. For example, CAT and ACT are anagrams, so we can skip ACT word completely. Then in all places where we have CAT in the output we can place ACT too.
We can also store and reuse intermediate results. Let's say we try to use word ACTA, run `process` function for remaining letters and get 10000 strings that we can build using these remaining letters. It took us a lot of time to calculate these 10000 strings. Then instead of word ACTA we try to use two words A CAT and call `process` function again to calculate what we can build using the same remaining letters while we can reuse already calculated result. It may take a lot of memory, but can speed up calculations for big inputs.

**Comment by pavlo-liapota** [comment]
I have pushed one more commit. It does not improve performance but makes `process` function more readable.

**Comment by pavlo-liapota** [comment]
And this commit implements this optimization:
> There are a lot of words that are anagrams of each other. We can keep just one word from these groups, run the algorithm and then update output to use other words too. For example, CAT and ACT are anagrams, so we can skip ACT word completely. Then in all places where we have CAT in the output we can place ACT too.

If we have `CAT CAT` as input, then process function will return only one anagram `ACT ACT`, and then `permuteAllPossibleWordsInGroups` function will generate result:
```
ACT ACT
ACT CAT
CAT CAT
```

Test is failing now because the order of anagrams and words inside anagram has changed.
EDIT: it returns less results than expected, I will find a reason.

**Comment by dmcg** [comment]
That's really cool, atlhough as you say it is missing a lot of results, so that may be the cause of the speedup.

Loosing the collector I'm in two minds about - I didn't like the collector to start with, and wanted to find a solution where each step returned a list that was flattened by its parent. But the collector has the advantage that it could allow the calling code to cancel when it has enough results - which is the sort of thing that is handy for the sort of interactive app I'm thinking of.

**Comment by dmcg** [comment]
BTW Some results for different input lengths, for the current main branch

Refactoring To (13 letters) 554 ± 36
Refactoring To K (14 letters) Duration 1372 ± 6
Refactoring To Ko (15 letters) Duration 5341 ± 37
Refactoring To Kot (16 letters) Duration 10453 ± 18

**Comment by dmcg** [comment]
Another interesting wrinkle - at least for versions prior to the grouping by anagram, there is a significant speed up just by ordering the input by size descending.

**Comment by pavlo-liapota** [comment]
I have fixed an issue. Now it returns all results.
I have written a test (but didn't commit it) where I order expected and actual results before comparing them and it succeeded  👍 

I order in following way:
```
fun List<String>.order() =
    map { it.split(" ").sorted().joinToString(" ") }
        .sorted()
```

**Comment by pavlo-liapota** [comment]
>Another interesting wrinkle - at least for versions prior to the grouping by anagram, there is a significant speed up just by ordering the input by size descending.

Do you mean there is a speed up by ordering words?

**Comment by pavlo-liapota** [comment]
>Loosing the collector I'm in two minds about - I didn't like the collector to start with, and wanted to find a solution where each step returned a list that was flattened by its parent. But the collector has the advantage that it could allow the calling code to cancel when it has enough results - which is the sort of thing that is handy for the sort of interactive app I'm thinking of.

I see. Maybe instead we can add a parameter that will say how much results should be returned? Or if we want to be more general: a lamba that will return true if there are enough results.

**Comment by dmcg** [comment]
> > Another interesting wrinkle - at least for versions prior to the grouping by anagram, there is a significant speed up just by ordering the input by size descending.
> 
> Do you mean there is a speed up by ordering words?

Yes, about 30% on my baseline for REFACTORING TO

**Comment by dmcg** [comment]
This is some great work, thank you.

You may be interested in some property tests that I added (they're on the preview branch https://github.com/dmcg/bumper-generator/tree/preview) and the next episode showing them being added (https://youtu.be/010m2YkSmS8).

If it's OK with you I will take your ideas and implement them on top of my main, or maybe merge your code and then refactor it as I try to understand what you have done. If you DM me your postal address on Twitter I'll get a copy of our book sent to you as promised.

**Comment by pavlo-liapota** [comment]
>You may be interested in some property tests that I added (they're on the preview branch https://github.com/dmcg/bumper-generator/tree/preview) and the next episode showing them being added (https://youtu.be/010m2YkSmS8).

Thanks! I will check.

>If it's OK with you I will take your ideas and implement them on top of my main

Sure, let me know if you have any questions.

>If you DM me your postal address on Twitter I'll get a copy of our book sent to you as promised.

Thanks, will do :)

**Comment by pavlo-liapota** [comment]
I have added another optimization. It stores results (anagrams and candidate words for a specific letters) and then reuses them. It makes small cases a bit slower, but helps a lot for big inputs as we don't calculate that was already calculated.
Now `REFACTORING TO KOTLIN` takes less than 2 minutes!

Also this cache can be reused in succeeding calls. So if it is expected that we calculate anagrams for different inputs then it can help even more.

**Comment by pavlo-liapota** [comment]
>https://youtu.be/010m2YkSmS8

I liked the video! Especially how expressive error messages are and how you have reused anagram calculations between tests, very nice 👍

**Comment by dmcg** [comment]
> I have added another optimization. It stores results (anagrams and candidate words for a specific letters) and then reuses them. It makes small cases a bit slower, but helps a lot for big inputs as we don't calculate that was already calculated. Now `REFACTORING TO KOTLIN` takes less than 2 minutes!
> 
> Also this cache can be reused in succeeding calls. So if it is expected that we calculate anagrams for different inputs then it can help even more.

I'm glad you're having as much fun with this as I am!

**Comment by dmcg** [comment]
> > https://youtu.be/010m2YkSmS8
> 
> I liked the video! Especially how expressive error messages are and how you have reused anagram calculations between tests, very nice 👍

Thank you. It's nice having the time to explore a topic and post what I'm learning.

**Comment by dmcg** [comment]
This is interesting https://docs.google.com/spreadsheets/d/18jnBYfv9y05qaDGZrmoW1u6Uldf0Zy89V9aKMxZbfpw/edit?usp=sharing

I think that it shows that runtime is proportional to the number of results, and that both are exponentialish. But if runtime is just a factor of result size, it suggests that we can't beat the O(C^n) that is the natural complexity?

**Comment by pavlo-liapota** [comment]
Yes, sounds right. We cannot beat it.
But if we look at it from the other side, what would be an application to have millions of anagrams? Probably it can be more interesting to get only some anagrams fast and potentially filtered by a specific criteria?

**Comment by pavlo-liapota** [comment]
For example, we can say that we want to generate an anagram that can read like a real phrase.
For that we may generate all anagrams and then filter those that we need but that will take a lot of time and we cannot optimize that.
Alternatively, we can try to implement algorithm that finds only one or few anagrams but those that we need then we can try optimize it so it is done fast.

**Comment by dmcg** [comment]
I certainly want to find the more interesting anagrams. I suppose the question is how much words can be filtered as we generate, or whether the best strategy is to score afterwards. Given the C^n I guess we’re forced down the first route for long inputs, which is fine.

**Comment by pavlo-liapota** [comment]
`process` function is very much optimized now. Most of the time is spend inside `permuteAllPossibleWordsInGroups` function, which just generates more anagrams.

**Comment by pavlo-liapota** [comment]
>If you DM me your postal address on Twitter I'll get a copy of our book sent to you as promised.

I get: `@duncanmcg can’t be messaged`

**Comment by dmcg** [comment]
> > If you DM me your postal address on Twitter I'll get a copy of our book sent to you as promised.
> 
> I get: `@duncanmcg can’t be messaged`

I've followed you back - maybe that will fix it

**Comment by dmcg** [comment]
> > If you DM me your postal address on Twitter I'll get a copy of our book sent to you as promised.
> 
> I get: `@duncanmcg can’t be messaged`

I've followed you back - that might fix it.

**Comment by pavlo-liapota** [comment]
I have rebased my first commit onto new master. And have excluded my other commits that implement a cache, they cannot be easily merged with current master. But I have kept them in `use-cache` branch in my fork.

**Comment by dmcg** [comment]
Interestingly for me that slows things down

REFACTORING : Duration 38 ± 43, Result count 9017
REFACTORING T : Duration 23 ± 1, Result count 15108
REFACTORING TO : Duration 138 ± 2, Result count 128270
REFACTORING TO K : Duration 342 ± 0, Result count 222225
REFACTORING TO KO : Duration 1508 ± 0, Result count 1038259
REFACTORING TO KOT : Duration 3150 ± 0, Result count 1609238
REFACTORING TO KOTL : Duration 11340 ± 0, Result count 5412104

compared to current

34
24
128
330
1307
2676
10705

I know that the letters change made a huge difference in the initial commit, so I assume that the other macro-optimizations have meant that we call the two functions fewer enough times to make the overhead worth it.

**Comment by dmcg** [comment]
I do really appreciate having someone else working on this - sorry to never have merged this one!

**Comment by pavlo-liapota** [comment]
>Interestingly for me that slows things down

Aha, I will double check the code if I missed something or it just doesn't help after other optimizations as you said.

**Comment by pavlo-liapota** [comment]
Hm, can you run speed tests again?

I have these times for master:
```
REFACTORING : Duration 33 ± 21, Result count 9017
REFACTORING T : Duration 26 ± 1, Result count 15108
REFACTORING TO : Duration 123 ± 1, Result count 128270
REFACTORING TO K : Duration 331 ± 0, Result count 222225
REFACTORING TO KO : Duration 1254 ± 0, Result count 1038259
REFACTORING TO KOT : Duration 2553 ± 0, Result count 1609238
REFACTORING TO KOTL : Duration 10962 ± 0, Result count 5412104
```

And these times for this PR:
```
REFACTORING : Duration 30 ± 23, Result count 9017
REFACTORING T : Duration 21 ± 2, Result count 15108
REFACTORING TO : Duration 112 ± 9, Result count 128270
REFACTORING TO K : Duration 268 ± 0, Result count 222225
REFACTORING TO KO : Duration 1157 ± 0, Result count 1038259
REFACTORING TO KOT : Duration 2535 ± 0, Result count 1609238
REFACTORING TO KOTL : Duration 8880 ± 0, Result count 5412104
```

**Comment by dmcg** [comment]
Will do

**Comment by dmcg** [comment]
On my last-gen Intel MacBook Pro, 2.3 GHz Quad-Core Intel Core i7, Java 15

Before:

```
REFACTORING : Duration 19 ± 14, Result count 9017
REFACTORING T : Duration 26 ± 2, Result count 15108
REFACTORING TO : Duration 158 ± 14, Result count 128270
REFACTORING TO K : Duration 416 ± 0, Result count 222225
REFACTORING TO KO : Duration 1590 ± 0, Result count 1038259
REFACTORING TO KOT : Duration 2778 ± 0, Result count 1609238
REFACTORING TO KOTL : Duration 11748 ± 0, Result count 5412104
```

After:

```
REFACTORING : Duration 21 ± 19, Result count 9017
REFACTORING T : Duration 19 ± 2, Result count 15108
REFACTORING TO : Duration 141 ± 21, Result count 128270
REFACTORING TO K : Duration 359 ± 0, Result count 222225
REFACTORING TO KO : Duration 1538 ± 0, Result count 1038259
REFACTORING TO KOT : Duration 2511 ± 0, Result count 1609238
REFACTORING TO KOTL : Duration 9764 ± 0, Result count 5412104
```

You win on two out of three!

**Comment by dmcg** [comment]
And, for some reason, a little faster still having merged!

```
REFACTORING : Duration 27 ± 22, Result count 9017
REFACTORING T : Duration 17 ± 0, Result count 15108
REFACTORING TO : Duration 104 ± 2, Result count 128270
REFACTORING TO K : Duration 256 ± 0, Result count 222225
REFACTORING TO KO : Duration 1254 ± 0, Result count 1038259
REFACTORING TO KOT : Duration 2607 ± 0, Result count 1609238
REFACTORING TO KOTL : Duration 8937 ± 0, Result count 5412104
```

**Comment by dmcg** [comment]
And now, for posterity, first results on M2 MacBook Air, with Java 15 still under Rosetta

REFACTORING : Duration 16 ± 5, Result count 9017
REFACTORING T : Duration 21 ± 1, Result count 15108
REFACTORING TO : Duration 120 ± 9, Result count 128270
REFACTORING TO K : Duration 276 ± 0, Result count 222225
REFACTORING TO KO : Duration 1145 ± 0, Result count 1038259
REFACTORING TO KOT : Duration 2075 ± 0, Result count 1609238
REFACTORING TO KOTL : Duration 7824 ± 0, Result count 5412104

**Comment by dmcg** [comment]
M2 MacBook Air, Java 19, native

REFACTORING : Duration 9 ± 11, Result count 9017
REFACTORING T : Duration 11 ± 0, Result count 15108
REFACTORING TO : Duration 66 ± 2, Result count 128270
REFACTORING TO K : Duration 177 ± 0, Result count 222225
REFACTORING TO KO : Duration 645 ± 0, Result count 1038259
REFACTORING TO KOT : Duration 1158 ± 0, Result count 1609238
REFACTORING TO KOTL : Duration 4487 ± 0, Result count 5412104

**Comment by pavlo-liapota** [comment]
Interesting!
I am using Java 17

**Pull request merged**
