### PR TITLE
Use cache to avoid computing same operations several times

### PR DESCRIPTION
**Pull request by pavlo-liapota**
I have reimplemented my cache solution for new master branch.
It has reduced time for `REFACTORING TO KOTL` by half!

### CODE REVIEW

**Comment by dmcg** [comment]
Ooh, WordTree is an interesting abstraction.

One piece of structural feedback - I think the cache should be a property of the AnagramGenerator class. That way it can be used or discarded with the instance.

**Comment by dmcg** [comment]
I’ll be interested to see the cache behaviour. How much does it help in a single invocation of anagramsFor, or is its major effect between multiple invocations with the same input?

The next stage for me is an interactive session, selecting one or more words in the solution and drilling down from there. I could reuse the AnagramGenerator and its cache for this, or maybe return more context with the results to be fed back into the next call. 

Still thinking it through…

**Comment by pavlo-liapota** [comment]
> How much does it help in a single invocation of anagramsFor, or is its major effect between multiple invocations with the same input?

I think we can just check number of calls to `instrumentation`, right?

**Comment by pavlo-liapota** [comment]
> I’ll be interested to see the cache behaviour. How much does it help in a single invocation of anagramsFor

I have tested for `REFACTORING TO` input.
In current implementation `MinusLettersInInvocation` is called `451 269` times.
And with cache it is called `88 323` times.

**Comment by dmcg** [comment]
Thank you. I think that I'm going to park this for future inspiration while I work out the workflow around drilling down into words.

**Comment by dmcg** [comment]
Closed as #6 includes this change

**Pull request closed without merging**
