### PR TITLE
Generate unique anagrams and avoid removal of duplicates

### PR DESCRIPTION
**Pull request by pavlo-liapota**
This has reduced time for `REFACTORING TO KOTL` from 4s to 3.5s.
Win is mainly because we don't need to sort words inside the anagram.

### CODE REVIEW

**Comment by dmcg** [comment]
You know what - this is so good I'm just going to merge it and then understand it on master

**Comment by dmcg** [comment]
Is the caching now cheating on the timings - basically the short input runs will be priming the cache for the later longer runs, and the first of each of the long runs will prime the cache and make subsequent runs quicker?

I kind of want a cache where it helps within an exploration of a particular input - I know that I want anagrams of say "EVENT SOURCING" so I start a session and the cache helps during that session. From that perspective the lifespan of the AnagramGenerator and cache should be different (I now realise), as the AnagramGenerator is doing the up-front work that applies to any use, but the cache is session specific.

Anyhoo, awsome work Pavlo, thank you

**Comment by pavlo-liapota** [comment]
> Is the caching now cheating on the timings

No, I have added parameter `keepCache` and made it `false` by default (line 16).
If it is false, then it removes all cache after each call.
If we make it `true` then speed tests will work even faster. But for big inputs the most time is spent in function `permuteInto` anyway (that one that generates all results and has exponential growth) and that one does not use cache.

**Comment by pavlo-liapota** [comment]
> I'm just going to merge it and then understand it on master

I will try to write some description about it.

**Comment by pavlo-liapota** [comment]
> I kind of want a cache where it helps within an exploration of a particular input

I think current implementation of cache can be helpful for your scenario.
`process` function calculates all possible word sequences in anagrams and present them in a tree. Traversing a tree and generating all permutations of anagram words (`permuteInto()` function) takes a lot of time, but if you don't need all results then we just don't need to do this.

**Pull request merged**
